config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "twips#index"

  resources :twips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twip.rb
class Twip < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :twips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/twips_controller.rb
class TwipsController < ApplicationController
  before_action :set_twip, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, expect: [:index, :show]

  # GET /twips or /twips.json
  def index
    @twips = Twip.all.order("created_at DESC")
    @twip = Twip.new
  end

  # GET /twips/1 or /twips/1.json
  def show
  end

  # GET /twips/new
  def new
    @twip = current_user.twips.build
  end

  # GET /twips/1/edit
  def edit
  end

  # POST /twips or /twips.json
  def create
    @twip = current_user.twips.build(twip_params)

    respond_to do |format|
      if @twip.save
        format.html { redirect_to root_path, notice: "Twip was successfully created." }
        format.json { render :show, status: :created, location: @twip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twips/1 or /twips/1.json
  def update
    respond_to do |format|
      if @twip.update(twip_params)
        format.html { redirect_to twip_url(@twip), notice: "Twip was successfully updated." }
        format.json { render :show, status: :ok, location: @twip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twips/1 or /twips/1.json
  def destroy
    @twip.destroy

    respond_to do |format|
      format.html { redirect_to twips_url, notice: "Twip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twip
      @twip = Twip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twip_params
      params.require(:twip).permit(:twip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twips_helper.rb
module TwipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twipper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div> 
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div> 
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-4">Twipper</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New twip', new_twip_path, class: "button is-info is-inverted" %>
            </p>
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= button_to "Log out", destroy_user_session_path, 
                                          method: :delete, 
                                          data: { turbo: false },
                                          class: "button is-info" %>
              </p>
            <% else %>
              <p class="control">
                <%= link_to "Sign In", new_user_session_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to "Sign Up", new_user_registration_path, class: "button is-info" %>
              </p>
            <% end %>
          </div>
        </div>
      </div>

    </nav>

    <%= yield %>
  </body>
</html>

app/views/twips/_feed.html.erb
<div class="column is-half">
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/64x64.png">
      </p>
    </figure>
    <div class="media-content">
      <%= render 'form' %>
    </div>
  </article>

<% @twips.each do |twip| %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img src="https://bulma.io/images/placeholders/64x64.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= twip.user.name %></strong><br/>
          <small><%= twip.user.username %></small><br/>
          <p><%= twip.twip %></p>
        </div>
        <nav class="level">
          <div class="level-left is-mobile">
            <%= link_to twip, class: "level-item" do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to edit_twip_path(twip), class: "level-item" do %>
              <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to twip, method: :delete, data: { confirm: "Are you sure you want to trash this twip?"} do %>
              <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
            <% end %>
          </div>
        </nav>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/twips/_form.html.erb
<%= simple_form_for(@twip) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :twip, label: "Twip about it", input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, placeholder: "Compose a new twip..." %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/twips/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a class="panel-block">
      Trend 1
    </a>
    <a class="panel-block">
      Trend 2
    </a>
    <a class="panel-block">
      Trend 3
    </a>
    <a class="panel-block">
      Trend 4
    </a>
    <a class="panel-block">
      Trend 5
    </a>
  </nav>
</div>

app/views/twips/_twip.html.erb
<div id="<%= dom_id twip %>">
  <p>
    <strong>Twip:</strong>
    <%= twip.twip %>
  </p>

</div>

app/views/twips/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32-32">
          <img src="https://bulma.io/images/placeholders/64x64.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>John Babble</strong>
            <small>@jbabble</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  </nav>
</div>

app/views/twips/edit.html.erb
<h1>Editing twip</h1>

<%= render "form", twip: @twip %>

<br>

<div>
  <%= link_to "Show this twip", @twip %> |
  <%= link_to "Back to twips", twips_path %>
</div>

app/views/twips/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'trends' %>
      <%= render 'feed' %>
      <%= render 'who-to-follow'%>
    </div>
  </div>
</section>

app/views/twips/new.html.erb
<h1>New twip</h1>

<%= render "form", twip: @twip %>

<br>

<div>
  <%= link_to "Back to twips", twips_path %>
</div>

app/views/twips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @twip %>

<div>
  <%= link_to "Edit this twip", edit_twip_path(@twip) %> |
  <%= link_to "Back to twips", twips_path %>

  <%= button_to "Destroy this twip", @twip, method: :delete %>
</div>